name: Code Coverage

on: [pull_request]

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Run tests with coverage
        run: |
          dotnet test --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=lcov \
            /p:CoverletOutput=coverage/

      - name: Locate LCOV file
        id: find_cov_ref
        run: |
          echo "file=$(find . -type f -name 'coverage.info' -print -quit)" >> $GITHUB_OUTPUT

      - name: Upload code coverage for ref branch
        if: steps.find_cov_ref.outputs.file
        uses: actions/upload-artifact@v4
        with:
          name: ref-coverage.info
          path: ${{ steps.find_cov_ref.outputs.file }}

  checks:
    needs: base_branch_cov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v4
        with:
          name: ref-coverage.info
          path: .

      - name: Run tests with coverage
        run: |
          dotnet test --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=lcov \
            /p:CoverletOutput=coverage/

      - name: Locate LCOV file
        id: find_cov
        run: |
          echo "file=$(find . -type f -name 'coverage.info' -print -quit)" >> $GITHUB_OUTPUT

      - name: Generate Barecheck Code Coverage report
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: ${{ steps.find_cov.outputs.file }}
          base-lcov-file: "./ref-coverage.info"
          minimum-ratio: 0
          send-summary-comment: true
          show-annotations: "warning"
