name: .NET Core CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build & Test with Coverage
        run: |
          dotnet test --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            --collect:"XPlat Code Coverage;Format=cobertura"

      - name: Merge coverage reports
        run: |
          find . -name 'coverage.cobertura.xml' -print
          dotnet tool install --global dotnet-coverage
          dotnet-coverage merge --output coverage.cobertura.xml --output-format cobertura \
            $(find . -type f -name 'coverage.cobertura.xml')

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.cobertura.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/test_results.trx'

      - name: Print coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.cobertura.xml'
          badge: true
          indicators: true
